### ISSUE TITLE
最終的に出力されるシングルマニフェストファイルが分割されたものになってしまう

### ISSUE THREAD

**Issue by junjanjon** [unity3d-jp/SeparatedAssetBundleBuild#2]
既存のものと UTJ.SeparatedAssetBundleBuild.BuildAssetBundles を使ってビルドしたものでシングルマニフェストファイルに相違がある場合があります。
UTJ.SeparatedAssetBundleBuild.BuildAssetBundles を使うと、ビルドごとにシングルマニフェストファイルを上書きしていきます。そのため、最終的に出力されているシングルマニフェストファイルは最後のビルドに含まれるもののみになります。

最終的に出力されるシングルマニフェストファイルが分割されたものであることをREADMEへ明記してほしいです。

**Comment by wotakuro** [comment]
ご指摘ありがとうございます。
シングルマニュフェストファイルの事を失念しておりました。

READMEへ明記いたしましたので、どうぞ宜しくお願いいたします。

**Comment by junjanjon** [comment]
ご対応ありがとうございました！
